### ISSUE TITLE
Duplicated Max Threads setting on Import Screen

### ISSUE THREAD

**Issue by ksulikow** [Capgemini/xrm-datamigration-xrmtoolbox#10]
**Describe the bug**

**To Reproduce**
Go to Import Screen and you will see: 
![image](https://user-images.githubusercontent.com/22191530/110330691-fc454a00-8015-11eb-930b-6f71c76c4d28.png)

**Expected behavior**
Only one setting for threads

**Comment by realekhor** [comment]
This bug has been addressed in the make-open-source pull request.
