### ISSUE TITLE
No file/schema validation on data import

### ISSUE THREAD

**Issue by joaozorro** [Capgemini/xrm-datamigration-xrmtoolbox#11]
**Describe the bug**
When importing a csv file there is no validation on the schema file that os selected. you can select any type of file the tools will try to import and report no errors.

**To Reproduce**
Tab "Data Import" , Select CSV, select a txt file and continue

**Expected behavior**
File Schema validation and error 

.

**Comment by realekhor** [comment]
this issue has now been addressed by the make-open-source pull request
