### ISSUE TITLE
"Show system attributes" toggle switch does not refresh the currently displayed list

### ISSUE THREAD

**Issue by mjahlv** [Capgemini/xrm-datamigration-xrmtoolbox#22]
It is not immediately clear that this toggle does anything when an entity is opened. Would it be possible to refresh the list of attributes for the currently selected entity when this toggle is interacted with?

![image](https://user-images.githubusercontent.com/59883805/115748287-f02b0700-a38d-11eb-9e51-a3010846da4b.png)

**Comment by tdashworth** [comment]
@danroche10 to investigate

**Comment by danroche10** [comment]
Resolved in PR #52
