### ISSUE TITLE
Positions of buttons are not consistent between Schema Config, Data Import and Data Export pages

### ISSUE THREAD

**Issue by mjahlv** [Capgemini/xrm-datamigration-xrmtoolbox#24]
Next and back buttons are in completely different positions. Also the labels and text boxes are in slightly different positions.

![image](https://user-images.githubusercontent.com/59883805/115749227-ce7e4f80-a38e-11eb-9e82-1f5a92532215.png)

![image](https://user-images.githubusercontent.com/59883805/115749267-d8a04e00-a38e-11eb-822f-6a6e0e062f2d.png)

![image](https://user-images.githubusercontent.com/59883805/115749316-e2c24c80-a38e-11eb-87cb-a5e2fc9fac68.png)

**Comment by tdashworth** [comment]
@danroche10 I think this has been done. If so please share some latest screenshots and close this ticket. :)
