### ISSUE TITLE
Unable to import Team Security Role associations.

### ISSUE THREAD

**Issue by simes1** [Capgemini/xrm-datamigration-xrmtoolbox#36]
**Describe the bug**
Unable to import Teams with Security Role associations.

**To Reproduce**
When importing teams with teamroles the schema appears to be created correctly and data exported but teams then fail to import with a "Sequence contains no matching element" error:

![image](https://user-images.githubusercontent.com/11423243/125574399-57e1549c-b761-4a59-b1bb-4ef282ad905f.png)

**Expected behaviour**
Teams to be importing along with their Security Role associations

**Additional context**
Trying to import Team owned Queues, Teams and their Security Roles.

**Comment by realekhor** [comment]
hi @simes1  we are looking investigating this issue.

**Comment by ksulikow** [comment]
> hi @simes1 we are investigating this issue.

I believe it works for JSON format - the problem is with CSV format only - can you confirm, please?

**Comment by simes1** [comment]
I have been using CSV format - I hadn't considered JSON but can retry when I get some time.

**Comment by realekhor** [comment]
@simes1  the latest fix should address the issue. please let me know it the issue is now fixed.
