### ISSUE TITLE
How do you stop the migration once the execution has begun? 

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/xrm-datamigration-xrmtoolbox#43]
**Is your feature request related to a problem? Please describe.**
Once the execution has begun, there's no clear way to stop the migration if desired.

**Describe the solution you'd like**
The "Execute" button could be converted to "Stop" which would use the available cancellation token to stop the migration.

**Comment by realekhor** [comment]
@tdashworth very valid request. I think this is also a quick win. I will prioritize this.

**Comment by tdashworth** [comment]
Completed by #44
