### ISSUE TITLE
No error logging

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/xrm-datamigration-xrmtoolbox#5]
It appears that if the engine crashes due to an unexpected, the UI never presents this to the user. I've seen two case of this:

1. When an Office365 connection string has been used but not supported.
2. When the batch limit is exceeded for writes to Dataverse. 

This results in the process looking frozen or paused which is quite confusing for the user.

**Comment by ksulikow** [comment]
@tdashworth I missed that, can I link it somehow to the issue I have just created ? https://github.com/Capgemini/xrm-datamigration-xrmtoolbox/issues/32
