### ISSUE TITLE
Multithreaded Processing

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/xrm-datamigration-xrmtoolbox#6]
**Describe the bug**
When running the Data Import, I get the below message in the console. 

```
Info:Starting Single Threaded processing, you must configure connection string for multithreaded processing adn set up max threads to more than 1
```

**To Reproduce**
I am running the migration via the XRM Toolbox plugin. I used the SDK authentication method.

**Comment by ksulikow** [comment]
> @tdashworth That is the trial environment which was created less than a month ago.
> 
> I tried both `Connection Wizard` and `OAuth` connection methods but it's not working either. 😔
> 
> Thanks for planning to fix this issue soon. Please keep me posted.

Multi threading processing is using currently CrmServiceClient Clone method which is only supported for OAuth connections:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.clone?view=dynamics-xrmtooling-ce-9

If you use connection string eg. with clientid and secret then it is working as I just tested it.

**Comment by ksulikow** [comment]
@tdashworth @LinnZawWin Can you try multithreading with the OAuth connection, please? The latest version 1.0.5 is using the Clone operation as I mentioned above, and it is working for me, be careful as you will see two sections for Thread Count - I opened a new issue for it, it will be fixed, for now set up both to eg 2 threads. Let me know if it works, please

**Comment by LinnZawWin** [comment]
@ksulikow Thanks for the fix. The initial issue was not just Multithreaded Processing, **Data Import process** was not working at all for any connection methods.

Now, I just tested version 1.0.5.0 and it is working for all types of Connection Methods for Single-Threaded processing.
Multithreaded Processing is working for OAuth, SDK Login Control and Client Id / Secret connection types.

**Comment by tdashworth** [comment]
@ksulikow can we close this now?
