### ISSUE TITLE
Data Import - Directory not mandatory

### ISSUE THREAD

**Issue by joaozorro** [Capgemini/xrm-datamigration-xrmtoolbox#8]
When importing data the field "What directory contains the source data" is not mandatory. the tools allows to continues the import process.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26481026/108698373-f884d400-74fb-11eb-9190-cf6d3de4e198.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/26481026/108698459-105c5800-74fc-11eb-9a38-5972bf09b6eb.png)

**Comment by realekhor** [comment]
@joaozorro  this issue should already be fixed in version 1.1.1. Is it ok to close this issue?

**Comment by realekhor** [comment]
![image](https://user-images.githubusercontent.com/29599766/126376742-dc96b2c3-044f-4cf2-b30e-74f1647acffe.png)

**Comment by joaozorro** [comment]
thanks

**Comment by realekhor** [comment]
thank you
